name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/portfolio
          TAG: ${{ github.sha }}
        run: |
          docker build -f .docker/Dockerfile -t ${IMAGE_NAME}:${TAG} .
          docker push ${IMAGE_NAME}:${TAG}
